### ISSUE TITLE
"Could not find ffi" error during build

### ISSUE THREAD

**Issue by samuelcolvin** [jekyll/docker#120]
I've just tried to get started with jekyll/docker using the command straight from the wikI:
```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll \
  -it -p 127.0.0.1:4000:4000 jekyll/jekyll
```

And I'm getting an error installing dependencies:
```
...
Using jekyll-sass-converter 1.3.0
Installing ffi 1.9.10 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10
Using activesupport 4.2.6
Using jekyll-coffeescript 1.0.1
Using sawyer 0.7.0
Installing nokogiri 1.6.7.2 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.7.2
An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find ffi-1.9.10 in any of the sources (Bundler::GemNotFound)
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
	from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<main>'
sh: can't kill pid 1562: No such process
```

system:
```
> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 186
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.63 GiB
Name: ***
ID: P54N:3ITE:AHYE:LOOZ:JLUF:E5VA:TIGK:XFJW:TXM4:IUQF:FX6Z:3VGK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

Let me know if you need anymore information or if I'm being very dumb in some way?

**Comment by samuelcolvin** [comment]
Realised this was due to having `Gemfile` and `Gemfile.lock` in the local directory, rename them fixed the problem.

**Comment by tabdulradi** [comment]
Deleting `Gemfile.lock` worked too. Thanks.
