### ISSUE TITLE
jekyll/jekyll:pages image problem

### ISSUE THREAD

**Issue by tivaliy** [jekyll/docker#183]
Executing command:
`$ docker run --rm -t -i -v "$PWD:/srv/jekyll" -p 4000:4000 jekyll/jekyll:pages jekyll serve --watch --incremental`
leads to an error: 

```
Unable to find image 'jekyll/jekyll:pages' locally
pages: Pulling from jekyll/jekyll
88286f41530e: Pull complete 
55c9e9766f9e: Pull complete 
1b05ffe7c18b: Pull complete 
9e7ee53408c0: Pull complete 
41544ef07e36: Pull complete 
b349851109e2: Pull complete 
Digest: sha256:f413fa4a2fd965eab5e55fbe426e5dbca67966ec0d44e0eb400ea5604b4014d5
Status: Downloaded newer image for jekyll/jekyll:pages
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find minitest-5.10.3 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /usr/local/bundle/gems/jekyll-3.5.2/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-3.5.2/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:23:in `load'
	from /usr/local/bundle/bin/jekyll:23:in `<main>'
```

**Comment by envygeeks** [comment]
Please check your Gemfile, clear your Gemfile.lock (delete it) and try again, we do not mess with your Gemfile.lock, we only attempt to install, so if there is a conflict that needs to be resolved it must be done by you.

**Comment by tivaliy** [comment]
@envygeeks , thanks for the tips.
The content of my Gemfile is:

```
source 'https://rubygems.org'
gem "github-pages", group: :jekyll_plugins
gem "jekyll-sitemap", group: :jekyll_plugins
```
I deleted Gemfile.lock and tried again, but without success.

Now, to make it work I had to modify command that looks like as follows:
`docker run --rm -t -i -v "$PWD:/srv/jekyll" -p 4000:4000 jekyll/jekyll:pages bundle exec jekyll serve --host=0.0.0.0 --watch --incremental`

**Comment by envygeeks** [comment]
I will see what I can figure out with your Gemfile today, thanks for the update!

**Comment by envygeeks** [comment]
This is actually a bug with Jekyll.  So I'll be shipping it off to them and seeing if I can work around it for now, but this is a pretty crazy bug, that shouldn't even exist...
