### ISSUE TITLE
Alpine 3.15 is not supported by sass-embedded. Please upgrade to Alpine 3.18

### ISSUE THREAD

**Issue by JV-conseil** [jekyll/docker#363]
**Liquid Exception: end of file reached in /srv/jekyll/_layouts/base.liquid
/usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `readbyte': end of file reached (EOFError)**

```logs
Requested labels: ubuntu-latest
Job defined at: ****/www/.github/workflows/jekyll-docker-gh-pages.yml@refs/heads/main
Waiting for a runner to pick up this job...
Job is waiting for a hosted runner to come online.
Job is about to start running on the hosted runner: GitHub Actions 4 (hosted)
Current runner version: '2.305.0'
##[group]Operating System
Ubuntu
22.04.2
LTS
##[endgroup]
##[group]Runner Image
Image: ubuntu-22.04
Version: 20230619.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230619.1.0/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230619.1.0
##[endgroup]
##[group]Runner Image Provisioner
2.0.238.1
##[endgroup]
##[group]GITHUB_TOKEN Permissions
Contents: read
Metadata: read
Pages: write
##[endgroup]
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:c85c95e3d7251135ab7dc9ce3241c5835cc595a9)
Download action repository 'actions/configure-pages@v3' (SHA:f156874f8191504dae5b037505266ed5dda6c382)
Download action repository 'actions/upload-pages-artifact@v1' (SHA:66b63f4a7de003f4f00cc8e9af4b83b8f2abdb96)
Getting action download info
Download action repository 'actions/upload-artifact@v3' (SHA:0b7f8abb1508181956e8e162db84b466c27e18ce)
Complete job name: build
##[group]Run actions/checkout@v3
with:
  repository: ****/www
  token: ***
  ssh-strict: true
  persist-credentials: true
  clean: true
  sparse-checkout-cone-mode: true
  fetch-depth: 1
  lfs: false
  submodules: false
  set-safe-directory: true
##[endgroup]
Syncing repository: ****/www
##[group]Getting Git version info
Working directory is '/home/runner/work/www/www'
[command]/usr/bin/git version
git version 2.41.0
##[endgroup]
Temporarily overriding HOME='/home/runner/work/_temp/54b6891b-6787-432e-a6c5-c22ee3dbc8f1' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
[command]/usr/bin/git config --global --add safe.directory /home/runner/work/www/www
Deleting the contents of '/home/runner/work/www/www'
##[group]Initializing the repository
[command]/usr/bin/git init /home/runner/work/www/www
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/runner/work/www/www/.git/
[command]/usr/bin/git remote add origin https://github.com/****/www
##[endgroup]
##[group]Disabling automatic garbage collection
[command]/usr/bin/git config --local gc.auto 0
##[endgroup]
##[group]Setting up auth
[command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
[command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
[command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
[command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
[command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
##[endgroup]
##[group]Fetching the repository
[command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +c220fdbefc12e0f828621bb415c0277b7fc46b8c:refs/remotes/origin/main
remote: Enumerating objects: 819, done.        
remote: Counting objects:   0% (1/819)        
remote: Counting objects:   1% (9/819)        
remote: Counting objects:   2% (17/819)        
remote: Counting objects:   3% (25/819)        
remote: Counting objects:   4% (33/819)        
remote: Counting objects:   5% (41/819)        
remote: Counting objects:   6% (50/819)        
remote: Counting objects:   7% (58/819)        
remote: Counting objects:   8% (66/819)        
remote: Counting objects:   9% (74/819)        
remote: Counting objects:  10% (82/819)        
remote: Counting objects:  11% (91/819)        
remote: Counting objects:  12% (99/819)        
remote: Counting objects:  13% (107/819)        
remote: Counting objects:  14% (115/819)        
remote: Counting objects:  15% (123/819)        
remote: Counting objects:  16% (132/819)        
remote: Counting objects:  17% (140/819)        
remote: Counting objects:  18% (148/819)        
remote: Counting objects:  19% (156/819)        
remote: Counting objects:  20% (164/819)        
remote: Counting objects:  21% (172/819)        
remote: Counting objects:  22% (181/819)        
remote: Counting objects:  23% (189/819)        
remote: Counting objects:  24% (197/819)        
remote: Counting objects:  25% (205/819)        
remote: Counting objects:  26% (213/819)        
remote: Counting objects:  27% (222/819)        
remote: Counting objects:  28% (230/819)        
remote: Counting objects:  29% (238/819)        
remote: Counting objects:  30% (246/819)        
remote: Counting objects:  31% (254/819)        
remote: Counting objects:  32% (263/819)        
remote: Counting objects:  33% (271/819)        
remote: Counting objects:  34% (279/819)        
remote: Counting objects:  35% (287/819)        
remote: Counting objects:  36% (295/819)        
remote: Counting objects:  37% (304/819)        
remote: Counting objects:  38% (312/819)        
remote: Counting objects:  39% (320/819)        
remote: Counting objects:  40% (328/819)        
remote: Counting objects:  41% (336/819)        
remote: Counting objects:  42% (344/819)        
remote: Counting objects:  43% (353/819)        
remote: Counting objects:  44% (361/819)        
remote: Counting objects:  45% (369/819)        
remote: Counting objects:  46% (377/819)        
remote: Counting objects:  47% (385/819)        
remote: Counting objects:  48% (394/819)        
remote: Counting objects:  49% (402/819)        
remote: Counting objects:  50% (410/819)        
remote: Counting objects:  51% (418/819)        
remote: Counting objects:  52% (426/819)        
remote: Counting objects:  53% (435/819)        
remote: Counting objects:  54% (443/819)        
remote: Counting objects:  55% (451/819)        
remote: Counting objects:  56% (459/819)        
remote: Counting objects:  57% (467/819)        
remote: Counting objects:  58% (476/819)        
remote: Counting objects:  59% (484/819)        
remote: Counting objects:  60% (492/819)        
remote: Counting objects:  61% (500/819)        
remote: Counting objects:  62% (508/819)        
remote: Counting objects:  63% (516/819)        
remote: Counting objects:  64% (525/819)        
remote: Counting objects:  65% (533/819)        
remote: Counting objects:  66% (541/819)        
remote: Counting objects:  67% (549/819)        
remote: Counting objects:  68% (557/819)        
remote: Counting objects:  69% (566/819)        
remote: Counting objects:  70% (574/819)        
remote: Counting objects:  71% (582/819)        
remote: Counting objects:  72% (590/819)        
remote: Counting objects:  73% (598/819)        
remote: Counting objects:  74% (607/819)        
remote: Counting objects:  75% (615/819)        
remote: Counting objects:  76% (623/819)        
remote: Counting objects:  77% (631/819)        
remote: Counting objects:  78% (639/819)        
remote: Counting objects:  79% (648/819)        
remote: Counting objects:  80% (656/819)        
remote: Counting objects:  81% (664/819)        
remote: Counting objects:  82% (672/819)        
remote: Counting objects:  83% (680/819)        
remote: Counting objects:  84% (688/819)        
remote: Counting objects:  85% (697/819)        
remote: Counting objects:  86% (705/819)        
remote: Counting objects:  87% (713/819)        
remote: Counting objects:  88% (721/819)        
remote: Counting objects:  89% (729/819)        
remote: Counting objects:  90% (738/819)        
remote: Counting objects:  91% (746/819)        
remote: Counting objects:  92% (754/819)        
remote: Counting objects:  93% (762/819)        
remote: Counting objects:  94% (770/819)        
remote: Counting objects:  95% (779/819)        
remote: Counting objects:  96% (787/819)        
remote: Counting objects:  97% (795/819)        
remote: Counting objects:  98% (803/819)        
remote: Counting objects:  99% (811/819)        
remote: Counting objects: 100% (819/819)        
remote: Counting objects: 100% (819/819), done.        
remote: Compressing objects:   0% (1/679)        
remote: Compressing objects:   1% (7/679)        
remote: Compressing objects:   2% (14/679)        
remote: Compressing objects:   3% (21/679)        
remote: Compressing objects:   4% (28/679)        
remote: Compressing objects:   5% (34/679)        
remote: Compressing objects:   6% (41/679)        
remote: Compressing objects:   7% (48/679)        
remote: Compressing objects:   8% (55/679)        
remote: Compressing objects:   9% (62/679)        
remote: Compressing objects:  10% (68/679)        
remote: Compressing objects:  11% (75/679)        
remote: Compressing objects:  12% (82/679)        
remote: Compressing objects:  13% (89/679)        
remote: Compressing objects:  14% (96/679)        
remote: Compressing objects:  15% (102/679)        
remote: Compressing objects:  16% (109/679)        
remote: Compressing objects:  17% (116/679)        
remote: Compressing objects:  18% (123/679)        
remote: Compressing objects:  19% (130/679)        
remote: Compressing objects:  20% (136/679)        
remote: Compressing objects:  21% (143/679)        
remote: Compressing objects:  22% (150/679)        
remote: Compressing objects:  23% (157/679)        
remote: Compressing objects:  24% (163/679)        
remote: Compressing objects:  25% (170/679)        
remote: Compressing objects:  26% (177/679)        
remote: Compressing objects:  27% (184/679)        
remote: Compressing objects:  28% (191/679)        
remote: Compressing objects:  29% (197/679)        
remote: Compressing objects:  30% (204/679)        
remote: Compressing objects:  31% (211/679)        
remote: Compressing objects:  32% (218/679)        
remote: Compressing objects:  33% (225/679)        
remote: Compressing objects:  34% (231/679)        
remote: Compressing objects:  35% (238/679)        
remote: Compressing objects:  36% (245/679)        
remote: Compressing objects:  37% (252/679)        
remote: Compressing objects:  38% (259/679)        
remote: Compressing objects:  39% (265/679)        
remote: Compressing objects:  40% (272/679)        
remote: Compressing objects:  41% (279/679)        
remote: Compressing objects:  42% (286/679)        
remote: Compressing objects:  43% (292/679)        
remote: Compressing objects:  44% (299/679)        
remote: Compressing objects:  45% (306/679)        
remote: Compressing objects:  46% (313/679)        
remote: Compressing objects:  47% (320/679)        
remote: Compressing objects:  48% (326/679)        
remote: Compressing objects:  49% (333/679)        
remote: Compressing objects:  50% (340/679)        
remote: Compressing objects:  51% (347/679)        
remote: Compressing objects:  52% (354/679)        
remote: Compressing objects:  53% (360/679)        
remote: Compressing objects:  54% (367/679)        
remote: Compressing objects:  55% (374/679)        
remote: Compressing objects:  56% (381/679)        
remote: Compressing objects:  57% (388/679)        
remote: Compressing objects:  58% (394/679)        
remote: Compressing objects:  59% (401/679)        
remote: Compressing objects:  60% (408/679)        
remote: Compressing objects:  61% (415/679)        
remote: Compressing objects:  62% (421/679)        
remote: Compressing objects:  63% (428/679)        
remote: Compressing objects:  64% (435/679)        
remote: Compressing objects:  65% (442/679)        
remote: Compressing objects:  66% (449/679)        
remote: Compressing objects:  67% (455/679)        
remote: Compressing objects:  68% (462/679)        
remote: Compressing objects:  69% (469/679)        
remote: Compressing objects:  70% (476/679)        
remote: Compressing objects:  71% (483/679)        
remote: Compressing objects:  72% (489/679)        
remote: Compressing objects:  73% (496/679)        
remote: Compressing objects:  74% (503/679)        
remote: Compressing objects:  75% (510/679)        
remote: Compressing objects:  76% (517/679)        
remote: Compressing objects:  77% (523/679)        
remote: Compressing objects:  78% (530/679)        
remote: Compressing objects:  79% (537/679)        
remote: Compressing objects:  80% (544/679)        
remote: Compressing objects:  81% (550/679)        
remote: Compressing objects:  82% (557/679)        
remote: Compressing objects:  83% (564/679)        
remote: Compressing objects:  84% (571/679)        
remote: Compressing objects:  85% (578/679)        
remote: Compressing objects:  86% (584/679)        
remote: Compressing objects:  87% (591/679)        
remote: Compressing objects:  88% (598/679)        
remote: Compressing objects:  89% (605/679)        
remote: Compressing objects:  90% (612/679)        
remote: Compressing objects:  91% (618/679)        
remote: Compressing objects:  92% (625/679)        
remote: Compressing objects:  93% (632/679)        
remote: Compressing objects:  94% (639/679)        
remote: Compressing objects:  95% (646/679)        
remote: Compressing objects:  96% (652/679)        
remote: Compressing objects:  97% (659/679)        
remote: Compressing objects:  98% (666/679)        
remote: Compressing objects:  99% (673/679)        
remote: Compressing objects: 100% (679/679)        
remote: Compressing objects: 100% (679/679), done.        
Receiving objects:   0% (1/819)
Receiving objects:   1% (9/819)
Receiving objects:   2% (17/819)
Receiving objects:   3% (25/819)
Receiving objects:   4% (33/819)
Receiving objects:   5% (41/819)
Receiving objects:   6% (50/819)
Receiving objects:   7% (58/819)
Receiving objects:   8% (66/819)
Receiving objects:   9% (74/819)
Receiving objects:  10% (82/819)
Receiving objects:  11% (91/819)
Receiving objects:  12% (99/819)
Receiving objects:  13% (107/819)
Receiving objects:  14% (115/819)
Receiving objects:  15% (123/819)
Receiving objects:  16% (132/819)
Receiving objects:  17% (140/819)
Receiving objects:  18% (148/819)
Receiving objects:  19% (156/819)
Receiving objects:  20% (164/819)
Receiving objects:  21% (172/819)
Receiving objects:  22% (181/819)
Receiving objects:  23% (189/819)
Receiving objects:  24% (197/819)
Receiving objects:  25% (205/819)
Receiving objects:  26% (213/819)
Receiving objects:  27% (222/819)
Receiving objects:  28% (230/819)
Receiving objects:  29% (238/819)
Receiving objects:  30% (246/819)
Receiving objects:  31% (254/819)
Receiving objects:  32% (263/819)
Receiving objects:  33% (271/819)
Receiving objects:  34% (279/819)
Receiving objects:  35% (287/819)
Receiving objects:  36% (295/819)
Receiving objects:  37% (304/819)
Receiving objects:  38% (312/819)
Receiving objects:  39% (320/819)
Receiving objects:  40% (328/819)
Receiving objects:  41% (336/819)
Receiving objects:  42% (344/819)
Receiving objects:  43% (353/819)
Receiving objects:  44% (361/819)
Receiving objects:  45% (369/819)
Receiving objects:  46% (377/819)
Receiving objects:  47% (385/819)
Receiving objects:  48% (394/819)
Receiving objects:  49% (402/819)
Receiving objects:  50% (410/819)
Receiving objects:  51% (418/819)
Receiving objects:  52% (426/819)
Receiving objects:  53% (435/819)
Receiving objects:  54% (443/819)
Receiving objects:  55% (451/819)
Receiving objects:  56% (459/819)
Receiving objects:  57% (467/819)
Receiving objects:  58% (476/819)
Receiving objects:  59% (484/819)
Receiving objects:  60% (492/819)
Receiving objects:  61% (500/819)
Receiving objects:  62% (508/819)
Receiving objects:  63% (516/819)
Receiving objects:  64% (525/819)
Receiving objects:  65% (533/819)
Receiving objects:  66% (541/819)
Receiving objects:  67% (549/819)
Receiving objects:  68% (557/819)
Receiving objects:  69% (566/819)
Receiving objects:  70% (574/819)
Receiving objects:  71% (582/819)
Receiving objects:  72% (590/819)
Receiving objects:  73% (598/819)
Receiving objects:  74% (607/819)
Receiving objects:  75% (615/819)
Receiving objects:  76% (623/819)
Receiving objects:  77% (631/819)
Receiving objects:  78% (639/819)
Receiving objects:  79% (648/819)
Receiving objects:  80% (656/819)
Receiving objects:  81% (664/819)
Receiving objects:  82% (672/819)
Receiving objects:  83% (680/819)
Receiving objects:  84% (688/819)
Receiving objects:  85% (697/819)
Receiving objects:  86% (705/819)
Receiving objects:  87% (713/819)
Receiving objects:  88% (721/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  89% (729/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  90% (738/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  91% (746/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  92% (754/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  93% (762/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  94% (770/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  95% (779/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  96% (787/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  97% (795/819), 16.21 MiB | 32.42 MiB/s
Receiving objects:  98% (803/819), 16.21 MiB | 32.42 MiB/s
remote: Total 819 (delta 130), reused 708 (delta 116), pack-reused 0        
Receiving objects:  99% (811/819), 16.21 MiB | 32.42 MiB/s
Receiving objects: 100% (819/819), 16.21 MiB | 32.42 MiB/s
Receiving objects: 100% (819/819), 24.50 MiB | 37.84 MiB/s, done.
Resolving deltas:   0% (0/130)
Resolving deltas:   1% (2/130)
Resolving deltas:   2% (3/130)
Resolving deltas:   3% (4/130)
Resolving deltas:   4% (6/130)
Resolving deltas:   5% (7/130)
Resolving deltas:   6% (8/130)
Resolving deltas:   7% (10/130)
Resolving deltas:   8% (11/130)
Resolving deltas:   9% (12/130)
Resolving deltas:  10% (13/130)
Resolving deltas:  11% (15/130)
Resolving deltas:  12% (16/130)
Resolving deltas:  13% (17/130)
Resolving deltas:  14% (19/130)
Resolving deltas:  15% (20/130)
Resolving deltas:  16% (21/130)
Resolving deltas:  17% (23/130)
Resolving deltas:  18% (24/130)
Resolving deltas:  19% (25/130)
Resolving deltas:  20% (26/130)
Resolving deltas:  21% (28/130)
Resolving deltas:  22% (29/130)
Resolving deltas:  23% (30/130)
Resolving deltas:  24% (32/130)
Resolving deltas:  25% (33/130)
Resolving deltas:  26% (34/130)
Resolving deltas:  27% (36/130)
Resolving deltas:  28% (37/130)
Resolving deltas:  29% (38/130)
Resolving deltas:  30% (39/130)
Resolving deltas:  31% (41/130)
Resolving deltas:  32% (42/130)
Resolving deltas:  33% (43/130)
Resolving deltas:  34% (45/130)
Resolving deltas:  35% (46/130)
Resolving deltas:  36% (47/130)
Resolving deltas:  37% (49/130)
Resolving deltas:  38% (50/130)
Resolving deltas:  39% (51/130)
Resolving deltas:  40% (52/130)
Resolving deltas:  41% (54/130)
Resolving deltas:  42% (55/130)
Resolving deltas:  43% (56/130)
Resolving deltas:  44% (58/130)
Resolving deltas:  45% (59/130)
Resolving deltas:  46% (60/130)
Resolving deltas:  47% (62/130)
Resolving deltas:  48% (63/130)
Resolving deltas:  49% (64/130)
Resolving deltas:  50% (65/130)
Resolving deltas:  51% (67/130)
Resolving deltas:  52% (68/130)
Resolving deltas:  53% (69/130)
Resolving deltas:  54% (71/130)
Resolving deltas:  55% (72/130)
Resolving deltas:  56% (73/130)
Resolving deltas:  57% (75/130)
Resolving deltas:  58% (76/130)
Resolving deltas:  59% (77/130)
Resolving deltas:  60% (78/130)
Resolving deltas:  61% (80/130)
Resolving deltas:  62% (81/130)
Resolving deltas:  63% (82/130)
Resolving deltas:  64% (84/130)
Resolving deltas:  65% (85/130)
Resolving deltas:  66% (86/130)
Resolving deltas:  67% (88/130)
Resolving deltas:  68% (89/130)
Resolving deltas:  69% (90/130)
Resolving deltas:  70% (91/130)
Resolving deltas:  71% (93/130)
Resolving deltas:  72% (94/130)
Resolving deltas:  73% (95/130)
Resolving deltas:  74% (97/130)
Resolving deltas:  75% (98/130)
Resolving deltas:  76% (99/130)
Resolving deltas:  77% (101/130)
Resolving deltas:  78% (102/130)
Resolving deltas:  79% (103/130)
Resolving deltas:  80% (104/130)
Resolving deltas:  81% (106/130)
Resolving deltas:  82% (107/130)
Resolving deltas:  83% (108/130)
Resolving deltas:  84% (110/130)
Resolving deltas:  85% (111/130)
Resolving deltas:  86% (112/130)
Resolving deltas:  87% (114/130)
Resolving deltas:  88% (115/130)
Resolving deltas:  89% (116/130)
Resolving deltas:  90% (117/130)
Resolving deltas:  91% (119/130)
Resolving deltas:  92% (120/130)
Resolving deltas:  93% (121/130)
Resolving deltas:  94% (123/130)
Resolving deltas:  95% (124/130)
Resolving deltas:  96% (125/130)
Resolving deltas:  97% (127/130)
Resolving deltas:  98% (128/130)
Resolving deltas:  99% (129/130)
Resolving deltas: 100% (130/130)
Resolving deltas: 100% (130/130), done.
From https://github.com/****/www
 * [new ref]         c220fdbefc12e0f828621bb415c0277b7fc46b8c -> origin/main
##[endgroup]
##[group]Determining the checkout info
##[endgroup]
##[group]Checking out the ref
[command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
Switched to a new branch 'main'
branch 'main' set up to track 'origin/main'.
##[endgroup]
[command]/usr/bin/git log -1 --format='%H'
'c220fdbefc12e0f828621bb415c0277b7fc46b8c'
##[group]Run actions/configure-pages@v3
with:
  token: ***
  enablement: false
##[endgroup]
##[group]Run docker run \
[36;1mdocker run \[0m
[36;1m-v /home/runner/work/www/www:/srv/jekyll \[0m
[36;1m-v /home/runner/work/www/www/_site:/srv/jekyll/_site \[0m
[36;1mjekyll/builder:latest \[0m
[36;1m/bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --trace --future"[0m
shell: /usr/bin/bash -e {0}
env:
  GITHUB_PAGES: true
##[endgroup]
Unable to find image 'jekyll/builder:latest' locally
latest: Pulling from jekyll/builder
df9b9388f04a: Pulling fs layer
837e9cfc7e43: Pulling fs layer
c7850f1a8c23: Pulling fs layer
6ca4c39baa3d: Pulling fs layer
daa3a8cb79d3: Pulling fs layer
227459856603: Pulling fs layer
6ca4c39baa3d: Waiting
daa3a8cb79d3: Waiting
227459856603: Waiting
c7850f1a8c23: Verifying Checksum
c7850f1a8c23: Download complete
df9b9388f04a: Verifying Checksum
df9b9388f04a: Download complete
837e9cfc7e43: Verifying Checksum
837e9cfc7e43: Download complete
daa3a8cb79d3: Verifying Checksum
daa3a8cb79d3: Download complete
df9b9388f04a: Pull complete
6ca4c39baa3d: Verifying Checksum
6ca4c39baa3d: Download complete
837e9cfc7e43: Pull complete
c7850f1a8c23: Pull complete
227459856603: Verifying Checksum
227459856603: Download complete
6ca4c39baa3d: Pull complete
daa3a8cb79d3: Pull complete
227459856603: Pull complete
Digest: sha256:439d7a3d94dd0547f47de5ff03fa910ba93c45dd748bc2b0cde6446d1c322a80
Status: Downloaded newer image for jekyll/builder:latest
Bundler 2.3.25 is running, but your lockfile was generated with 2.4.10. Installing Bundler 2.4.10 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.4.10
Installing bundler 2.4.10
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching concurrent-ruby 1.2.2
Fetching minitest 5.18.1
Installing minitest 5.18.1
Installing concurrent-ruby 1.2.2
Fetching public_suffix 5.0.1
Using bundler 2.4.10
Using colorator 1.1.0
Fetching duktape 2.7.0.0
Installing public_suffix 5.0.1
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using execjs 2.8.1
Fetching faraday-net_http 3.0.2
Installing faraday-net_http 3.0.2
Using ruby2_keywords 0.0.5
Using ffi 1.15.5
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Fetching google-protobuf 3.23.3 (x86_64-linux)
Installing duktape 2.7.0.0 with native extensions
Installing google-protobuf 3.23.3 (x86_64-linux)
Fetching racc 1.7.1
Installing racc 1.7.1 with native extensions
Using rb-fsevent 0.11.2
Using rexml 3.2.5
Fetching liquid 4.0.4
Installing liquid 4.0.4
Using mercenary 0.4.0
Fetching rouge 4.1.2
Installing rouge 4.1.2
Using safe_yaml 1.0.5
Fetching unicode-display_width 2.4.2
Installing unicode-display_width 2.4.2
Fetching webrick 1.8.1
Installing webrick 1.8.1
Fetching posix-spawn 0.3.15
Installing posix-spawn 0.3.15 with native extensions
Using jekyll-paginate 1.1.0
Fetching i18n 1.14.1
Installing i18n 1.14.1
Fetching tzinfo 2.0.6
Installing tzinfo 2.0.6
Fetching addressable 2.8.4
Installing addressable 2.8.4
Using em-websocket 0.5.3
Fetching katex 0.10.0
Installing katex 0.10.0
Fetching faraday 2.7.7
Installing faraday 2.7.7
Using rb-inotify 0.10.1
Using pathutil 0.16.2
Fetching sass-embedded 1.63.6 (x86_64-linux-musl)
Installing sass-embedded 1.63.6 (x86_64-linux-musl)
Fetching nokogiri 1.15.2 (x86_64-linux)
Installing nokogiri 1.15.2 (x86_64-linux)
Using kramdown 2.4.0
Fetching terminal-table 3.0.2
Installing terminal-table 3.0.2
Fetching activesupport 7.0.5
Installing activesupport 7.0.5
Fetching faraday-retry 2.2.0
Installing faraday-retry 2.2.0
Fetching listen 3.8.0
Installing listen 3.8.0
Fetching jekyll-sass-converter 3.0.0
Installing jekyll-sass-converter 3.0.0
Using kramdown-parser-gfm 1.1.0
Fetching kramdown-math-katex 1.0.1
Installing kramdown-math-katex 1.0.1
Using html-pipeline 2.14.3
Using jekyll-watch 2.2.1
Fetching jekyll 4.3.2
Installing jekyll 4.3.2
Fetching jekyll-avatar 0.7.0
Installing jekyll-avatar 0.7.0
Using jekyll-compose 0.12.0
Fetching jekyll-default-layout 0.1.5
Installing jekyll-default-layout 0.1.5
Using jekyll-feed 0.17.0
Fetching jekyll-include-cache 0.2.1
Installing jekyll-include-cache 0.2.1
Fetching jekyll-last-modified-at 1.3.0
Installing jekyll-last-modified-at 1.3.0
Using jekyll-mentions 1.6.0
Fetching jekyll-optional-front-matter 0.3.2
Installing jekyll-optional-front-matter 0.3.2
Fetching jekyll-readme-index 0.3.0
Installing jekyll-readme-index 0.3.0
Using jekyll-redirect-from 0.16.0
Fetching jekyll-relative-links 0.7.0
Installing jekyll-relative-links 0.7.0
Using jekyll-seo-tag 2.8.0
Using jekyll-sitemap 1.4.0
Fetching jekyll-titles-from-headings 0.5.3
Installing jekyll-titles-from-headings 0.5.3
Using jemoji 0.12.0
Bundle complete! 23 Gemfile dependencies, 62 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
       Jekyll Feed: Generating feed for posts tagged php
       Jekyll Feed: Generating feed for posts tagged javascript
       Jekyll Feed: Generating feed for posts tagged python
       Jekyll Feed: Generating feed for posts tagged git
       Jekyll Feed: Generating feed for posts tagged azure
       Jekyll Feed: Generating feed for posts tagged cloud
       Jekyll Feed: Generating feed for posts tagged postgresql
       Jekyll Feed: Generating feed for posts tagged django
       Jekyll Feed: Generating feed for posts tagged bash
       Jekyll Feed: Generating feed for posts tagged jekyll
       Jekyll Feed: Generating feed for posts tagged security
[31m  Liquid Exception: end of file reached in /srv/jekyll/_layouts/base.liquid[0m
/usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `readbyte': end of file reached (EOFError)
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `block in read'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/varint.rb:19:in `loop'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/varint.rb:19:in `read'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/connection.rb:62:in `block in read'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/connection.rb:61:in `synchronize'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/connection.rb:61:in `read'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/dispatcher.rb:76:in `receive_proto'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/dispatcher.rb:19:in `block (2 levels) in initialize'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/dispatcher.rb:18:in `loop'
	from /usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/dispatcher.rb:18:in `block in initialize'
##[error]Process completed with exit code 1.
Post job cleanup.
[command]/usr/bin/git version
git version 2.41.0
Temporarily overriding HOME='/home/runner/work/_temp/b434c8c3-98cf-422e-b3d0-145d6efa1300' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
[command]/usr/bin/git config --global --add safe.directory /home/runner/work/www/www
[command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
[command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
[command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
[command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
[command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
Cleaning up orphan processes
```

**Comment by JV-conseil** [comment]
Hi 👋

While waiting for @envygeeks to update this repo, I've pushed to Docker Hub an updated version for `jekyll/builder` image:
<https://hub.docker.com/r/jvconseil/jekyll-docker>

See also PR <https://github.com/envygeeks/jekyll-docker/pull/369>

Best,
@JV-conseil

**Comment by envygeeks** [comment]
This should be fixed by the new image work.
