### ISSUE TITLE
Quickstart Example Fails

### ISSUE THREAD

**Issue by teeks99** [jekyll/docker#372]
When trying to create a brand new site, I get a failure running the quickstart. 

```
~/tmp$ docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll sh -c "chown -R jekyll /usr/gem/ &&
 jekyll new test"                                                                                                       
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]                                                      
Running bundle install in /srv/jekyll/test...                                                                           
  Bundler: Fetching gem metadata from https://rubygems.org/............                                                 
  Bundler: Resolving dependencies...                                                                                    
  Bundler: Using bundler 2.3.25                                                                                         
  Bundler: Using colorator 1.1.0                                                                                        
  Bundler: Fetching concurrent-ruby 1.2.2                                                                               
  Bundler: Using http_parser.rb 0.8.0                                                                                   
  Bundler: Fetching ffi 1.16.3                                                                                          
  Bundler: Using rb-fsevent 0.11.2                                                                                      
  Bundler: Fetching liquid 4.0.4                                                                                        
  Bundler: Using rouge 3.30.0                                                                                           
  Bundler: Using safe_yaml 1.0.5                                                                                        
  Bundler: Using unicode-display_width 1.8.0                                                                            
  Bundler: Using eventmachine 1.2.7                                                                                     
  Bundler: Using forwardable-extended 2.6.0                                                                             
  Bundler: Fetching rexml 3.2.6                                                                                         
  Bundler: Using mercenary 0.4.0                                                                                        
  Bundler: Fetching public_suffix 5.0.3                                                                                 
  Bundler: Using terminal-table 2.0.0                                                                                   
  Bundler: Using pathutil 0.16.2                                                                                        
  Bundler: Using em-websocket 0.5.3                                                                                     
  Bundler: Installing liquid 4.0.4                         
  Bundler: Installing rexml 3.2.6                                                                                       
  Bundler: Installing public_suffix 5.0.3                                                                               
  Bundler: Installing concurrent-ruby 1.2.2                                                                             
  Bundler: Fetching addressable 2.8.5                                                                                   
  Bundler: Using kramdown 2.4.0                                                                                         
  Bundler: Using kramdown-parser-gfm 1.1.0                                                                              
  Bundler: Installing ffi 1.16.3 with native extensions                                                                 
  Bundler: Fetching i18n 1.14.1                                                                                         
  Bundler: Installing addressable 2.8.5                                                                                 
  Bundler: Installing i18n 1.14.1                                                                                       
  Bundler: Using rb-inotify 0.10.1                                                                                      
  Bundler: Using sassc 2.4.0                                                                                            
  Bundler: Using jekyll-sass-converter 2.2.0                                                                              Bundler: Fetching listen 3.8.0                                                                                        
  Bundler: Installing listen 3.8.0                                                                                      
  Bundler: Using jekyll-watch 2.2.1                                                                                     
  Bundler: Using jekyll 4.2.2                                                                                           
  Bundler: Using jekyll-feed 0.17.0                                                                                     
  Bundler: Using jekyll-seo-tag 2.8.0                                                                                   
  Bundler: Using minima 2.5.1                                                                                           
  Bundler: Bundle complete! 7 Gemfile dependencies, 31 gems now installed.                                              
  Bundler: Use `bundle info [gemname]` to see where a bundled gem is installed.                                         
New jekyll site installed in /srv/jekyll/test. 
```

Then turning around and running serve:
```
~/tmp/test$ docker run --rm --volume="$PWD:/srv/jekyll:Z" -it jekyll/jekyll jekyll build
Fetching gem metadata from https://rubygems.org/...........
Using bundler 2.3.25
Fetching public_suffix 5.0.3
Using colorator 1.1.0
Installing public_suffix 5.0.3
Installing concurrent-ruby 1.2.2
Using http_parser.rb 0.8.0
Fetching ffi 1.16.3
Using forwardable-extended 2.6.0
Using rb-fsevent 0.11.2
Fetching rexml 3.2.6
Installing rexml 3.2.6
Fetching liquid 4.0.4
Installing ffi 1.16.3 with native extensions
Installing liquid 4.0.4
Using mercenary 0.4.0
Using rouge 3.30.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.8.0
Fetching addressable 2.8.5
Installing addressable 2.8.5
Using em-websocket 0.5.3
Fetching i18n 1.14.1
Installing i18n 1.14.1
Using pathutil 0.16.2
Using terminal-table 2.0.0
Using sassc 2.4.0
Using rb-inotify 0.10.1
Using jekyll-sass-converter 2.2.0
Fetching listen 3.8.0
Using jekyll-watch 2.2.1
Using jekyll 4.2.2
Using jekyll-seo-tag 2.8.0
Using minima 2.5.1
Bundle complete! 7 Gemfile dependencies, 31 gems now installed.
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Fetching rexml 3.2.6
Installing rexml 3.2.6
Fetching liquid 4.0.4
Installing ffi 1.16.3 with native extensions
Installing liquid 4.0.4
Using mercenary 0.4.0
Using rouge 3.30.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.8.0
Fetching addressable 2.8.5
Installing addressable 2.8.5
Using em-websocket 0.5.3
Fetching i18n 1.14.1
Installing i18n 1.14.1
Using pathutil 0.16.2
Using kramdown 2.4.0
Using terminal-table 2.0.0
Using kramdown-parser-gfm 1.1.0
Using sassc 2.4.0
Using rb-inotify 0.10.1
Using jekyll-sass-converter 2.2.0
Fetching listen 3.8.0
Installing listen 3.8.0
Using jekyll-watch 2.2.1
Using jekyll 4.2.2
Using jekyll-feed 0.17.0
Using jekyll-seo-tag 2.8.0
Using minima 2.5.1
Bundle complete! 7 Gemfile dependencies, 31 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 0.204 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
/usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bundle/bin/jekyll:27:in `load'
        from /usr/local/bundle/bin/jekyll:27:in `<main>'
```

**Comment by mahdy-asady** [comment]
You need to install `webrick` which is not mentioned in the documentations. 
`docker run --rm --volume="$PWD:/srv/jekyll:Z" jekyll/jekyll bundle add webrick`
then rerun the build process.

**Comment by envygeeks** [comment]
This should be fixed by the new image work.
