### ISSUE TITLE
Add Jekyll Paginate Gem

### ISSUE THREAD

**Issue by jhabdas** [jekyll/docker#74]
Building off the following image: https://hub.docker.com/r/jekyll/jekyll/

With this in the `_config`:

```yaml
gems: [jekyll-paginate]
```

Leads to this:

```
Configuration file: /Users/jhabdas/Developer/technologyadvice.github.io/_config.yml
/usr/local/lib/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- jekyll-paginate (LoadError)
	from /usr/local/lib/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<main>'
```

This is a common plugin. Why is it not included in the [Current Gems](https://github.com/jekyll/docker#current-gems)?

**Comment by Fluidbyte** [comment]
:+1:

**Comment by jhabdas** [comment]
Looks like the paginate gem is available with the `:pages` docker image. It'd be nice to see this more clearly defined in the README.

**Comment by envygeeks** [comment]
I do not keep track or list Github's dependencies, I leave that to them to do.  If you would like it to be included on all tags then ask that, I don't think you want the answer to your current question.
