### ISSUE TITLE
Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by catherinedevlin** [jekyll/docker#8]
RedCloth is failing to install due to a compilation error.
```
root@cd-gsa:~/proj/meyot.github.io# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
root@cd-gsa:~/proj/meyot.github.io# docker -v
Docker version 1.5.0, build a8a31ef
root@cd-gsa:~/proj/meyot.github.io# docker run --rm -v $(pwd):/srv/jekyll -p 127.0.0.1:4000:4000 jekyll/jekyll:stable jekyll s
/opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler/spec_set.rb:85:in `map!'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler/spec_set.rb:85:in `materialize'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler/definition.rb:132:in `specs'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler/definition.rb:177:in `specs_for'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler/definition.rb:166:in `requested_specs'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler/environment.rb:18:in `requested_specs'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler/runtime.rb:13:in `setup'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/bundler-1.9.1/lib/bundler.rb:122:in `setup'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
	from /opt/jekyll/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:16:in `<top (required)>'
	from /usr/bin/jekyll:14:in `load'
	from /usr/bin/jekyll:14:in `<main>'
```

**Comment by catherinedevlin** [comment]
Also present for jekyll/jekyll:beta, but *not* for jekyll/jekyll:server.

**Comment by envygeeks** [comment]
https://github.com/jekyll/docker/commit/9b5c7076328c65cb61e0be7b849797d150bf8945

**Comment by rolfedh** [comment]
Sorry - Novice here. Could you explain how you solved the problem?

**Comment by envygeeks** [comment]
@rolfedh if you have received an error (even similar to this one) please file a unique ticket with the error and if you can provide the source and at minimum let us know if you are using a Gemfile, custom gems or anything that is *not* the default besides typical jekyll source files.
